<?php

namespace AmjadIqbal\VueForge\Console;

use Illuminate\Console\Command;
use System\Classes\PluginManager;

/**
 * MakeVueWidget scaffolds a new VueForge-powered FormWidget: a PHP widget
 * class extending `AmjadIqbal\VueForge\FormWidgets\VueWidget`, and a paired
 * `<script setup lang="ts">` Vue 3 SFC stub, inside a target plugin.
 *
 * Usage: php artisan vueforge:make Acme.Blog TagInput
 */
class MakeVueWidget extends Command
{
    /**
     * @var string signature for the console command
     */
    protected $signature = 'vueforge:make
        {plugin : Target plugin identifier <info>(eg: Acme.Blog)</info>}
        {name : Name of the widget/component to generate <info>(eg: TagInput)</info>}
        {--force : Overwrite existing files.}';

    /**
     * @var string description of the console command
     */
    protected $description = 'Create a new VueForge-powered form widget and its Vue 3 component stub.';

    public function handle(): int
    {
        $pluginManager = PluginManager::instance();
        $pluginCode = $pluginManager->normalizeIdentifier($this->argument('plugin'));

        if (!$pluginManager->hasPlugin($pluginCode)) {
            $this->components->error("Unable to find plugin [{$pluginCode}]. Register it before running vueforge:make.");

            return self::FAILURE;
        }

        $name = $this->normalizeComponentName($this->argument('name'));
        [$vendor, $plugin] = array_pad(explode('.', $pluginCode), 2, null);
        $pluginDir = plugins_path(strtolower($vendor) . '/' . strtolower($plugin));

        $widgetPath = $pluginDir . '/formwidgets/' . $name . '.php';
        $componentPath = $pluginDir . '/assets/vue/' . $name . '.vue';

        if (!$this->option('force') && (file_exists($widgetPath) || file_exists($componentPath))) {
            $this->components->error('One or both target files already exist. Use --force to overwrite.');

            return self::FAILURE;
        }

        $this->writeFile($widgetPath, $this->buildWidgetStub($vendor, $plugin, $name));
        $this->writeFile($componentPath, $this->buildComponentStub($name));

        $this->components->warn(
            'The generated component imports useVueForge via a relative path across plugin '
            . 'folders (plugins/<vendor>/<plugin>/... -> plugins/amjadiqbal/vueforge/...). '
            . "This only resolves if [{$pluginCode}]'s own Vite dev server is configured with "
            . "server.fs.allow including the vueforge plugin directory (Vite restricts serving "
            . 'files outside its project root by default). See docs/VUE3_MIGRATION_GUIDE.md for details.'
        );

        $this->components->info("VueForge widget [{$name}] created in [{$pluginCode}].");

        $widgetCode = strtolower($vendor) . '-' . strtolower($plugin) . '-' . strtolower($name);

        $this->newLine();
        $this->line('Register the FormWidget in your plugin\'s Plugin::registerFormWidgets(), then use it in a fields.yaml:');
        $this->newLine();
        $this->line("    my_field:");
        $this->line("        label: My Field");
        $this->line("        type: {$widgetCode}");
        $this->newLine();
        $this->line("(the exact \"type\" code is whatever you register it as in registerFormWidgets() - {$widgetCode} is the suggested convention, matching vendor-plugin-widget.)");

        return self::SUCCESS;
    }

    protected function normalizeComponentName(string $name): string
    {
        $studly = str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', $name)));

        return $studly !== '' ? $studly : 'MyWidget';
    }

    protected function writeFile(string $path, string $contents): void
    {
        $dir = dirname($path);

        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($path, $contents);

        $this->line("<info>created:</info> {$path}");
    }

    protected function buildWidgetStub(string $vendor, string $plugin, string $name): string
    {
        $namespace = $vendor . '\\' . $plugin . '\\FormWidgets';

        return <<<PHP
        <?php

        namespace {$namespace};

        use AmjadIqbal\VueForge\FormWidgets\VueWidget;

        /**
         * {$name} is a VueForge form widget generated by `php artisan vueforge:make`.
         */
        class {$name} extends VueWidget
        {
            /**
             * @var string component is the Vue SFC this widget mounts.
             */
            public \$component = '{$name}';

            /**
             * @var string viteEntry points at the component's source file so
             * ViteResolver can resolve its built/dev asset.
             */
            public \$viteEntry = 'assets/vue/{$name}.vue';
        }

        PHP;
    }

    protected function buildComponentStub(string $name): string
    {
        // plugins/<vendor>/<plugin>/assets/vue/{Name}.vue -> plugins/amjadiqbal/vueforge/...
        // is always 4 directories up from the generated file's own directory,
        // since October plugins live exactly two levels below `plugins/`.
        $composablePath = '../../../../amjadiqbal/vueforge/assets/js/composables/useVueForge';

        return <<<VUE
        <script setup lang="ts">
        import { useVueForge } from '{$composablePath}';

        interface Props {
            modelValue?: Record<string, unknown> | unknown[];
            fieldName: string;
        }

        const props = defineProps<Props>();

        const { value } = useVueForge({
            initialValue: props.modelValue ?? {},
            fieldName: props.fieldName,
        });
        </script>

        <template>
            <div class="{$name}-widget">
                <!-- TODO: build the {$name} UI. `value` is a reactive ref kept
                     in sync with the form's hidden input on every change. -->
                <pre>{{ value }}</pre>
            </div>
        </template>

        <style scoped>
        .{$name}-widget {
            /* TODO: style me */
        }
        </style>

        VUE;
    }
}
